pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = 'dockerhub-creds'   // Jenkins credentials ID
        DOCKERHUB_REPO = 'namita850/public-repo'      // Docker Hub repo
        IMAGE_TAG = "${env.BUILD_NUMBER}"           // Unique image tag per build
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ynamita/argocd-jenkins-project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${DOCKERHUB_REPO}:${IMAGE_TAG} nginx-gitops"
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${DOCKERHUB_CREDENTIALS}", usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh "echo $PASSWORD | docker login -u $USERNAME --password-stdin"
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh "docker push ${DOCKERHUB_REPO}:${IMAGE_TAG}"
            }
        }

        stage('Logout from Docker Hub') {
            steps {
                sh "docker logout"
            }
        }

        stage('Update Deployment') {
            steps {
                script {
                    // Update deployment YAML with new image tag
                    sh "sed -i 's|image: ${DOCKERHUB_REPO}:.*|image: ${DOCKERHUB_REPO}:${IMAGE_TAG}|' k8s/nginx-deployment.yaml"
                    
                    // Commit & push to GitHub so Argo CD can deploy
                    sh """
                        git config user.email "jenkins@example.com"
                        git config user.name "Jenkins-CI"
                        git add k8s/nginx-deployment.yaml
                        git commit -m "Update Nginx image to ${IMAGE_TAG}"
                        git push origin main
                    """
                }
            }
        }
    }
}

