pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = 'dockerhub-creds'
        DOCKERHUB_REPO = 'namita850/public-repo'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/ynamita/argocd-jenkins-project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('nginx-gitops') {
                    sh 'ls -l'
                    sh "docker build -t ${DOCKERHUB_REPO}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: DOCKERHUB_CREDENTIALS,
                        usernameVariable: 'USERNAME',
                        passwordVariable: 'PASSWORD'
                    )
                ]) {
                    sh 'echo $PASSWORD | docker login -u $USERNAME --password-stdin'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh "docker push ${DOCKERHUB_REPO}:${IMAGE_TAG}"
            }
        }

        stage('Logout from Docker Hub') {
            steps {
                sh 'docker logout'
            }
        }

        stage('Update Deployment (GitOps trigger)') {
            steps {
                dir('nginx-gitops') {
                    sh """
                      sed -i 's|image: .*|image: ${DOCKERHUB_REPO}:${IMAGE_TAG}|' k8s/nginx-dep.yaml
                      git config user.email "jenkins@example.com"
                      git config user.name "Jenkins-CI"
                      git add k8s/nginx-dep.yaml
                      git commit -m "Update nginx image to ${IMAGE_TAG}"
                      git push origin main
                    """
                }
            }
        }
    }
}

